# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'TealiumBranchExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumBranchExample
  pod 'TealiumBranch', :path=> '../'
  pod 'tealium-swift/Lifecycle', '~> 2.12'
end
